apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
        - name: 2048-app-container
          image: duybo95/2048:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-app-service
  namespace: default
spec:
  selector:
    app: 2048-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
